resource "aws_iam_policy" "terraform_pike" {
  # checkov:skip=CKV_AWS_290: IAM policy requires broad write access for this module to function
  # checkov:skip=CKV_AWS_355: IAM policy requires wildcard resource for this module to function
  name_prefix = "terraform_pike"
  path        = "/"
  description = "Pike Autogenerated policy from IAC"

  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "VisualEditor0",
        "Effect" : "Allow",
        "Action" : [
          "iam:CreateRole",
          "iam:DeleteRole",
          "iam:DeleteRolePolicy",
          "iam:GetRole",
          "iam:GetRolePolicy",
          "iam:ListAttachedRolePolicies",
          "iam:ListInstanceProfilesForRole",
          "iam:ListRolePolicies",
          "iam:PassRole",
          "iam:PutRolePolicy"
        ],
        "Resource" : "*"
      },
      {
        "Sid" : "VisualEditor1",
        "Effect" : "Allow",
        "Action" : [
          "states:CreateActivity",
          "states:CreateStateMachine",
          "states:DeleteActivity",
          "states:DeleteStateMachine",
          "states:DescribeActivity",
          "states:DescribeStateMachine",
          "states:ListTagsForResource",
          "states:TagResource",
          "states:UntagResource",
          "states:UpdateStateMachine"
        ],
        "Resource" : "*"
      }
    ]
  })
}
